name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chetan/git-restore-mtime-action@v1.1
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            ~/.cargo/registry/cache/
            ~/.cargo/registry/index/
            target/
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo fmt
        run: |-
          rustup component add rustfmt
          cargo fmt -- --check
      - name: cargo build
        run: cargo build --all-features
      - name: cargo clippy
        run: |-
          rustup component add clippy
          cargo clippy -- -D warnings
      - name: cargo test
        run: cargo test --all-features
